// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emploitocndixmodule.proxies;

public class candidat extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "emploiTocndixModule.candidat";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		nom("nom"),
		prenom("prenom"),
		salaire_voulu("salaire_voulu"),
		email("email"),
		avis("avis"),
		commentaire("commentaire"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		candidat_offre("emploiTocndixModule.candidat_offre"),
		candidat_cv("emploiTocndixModule.candidat_cv"),
		candidat_motivation("emploiTocndixModule.candidat_motivation");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public candidat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "emploiTocndixModule.candidat"));
	}

	protected candidat(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject candidatMendixObject)
	{
		super(context, candidatMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("emploiTocndixModule.candidat", candidatMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a emploiTocndixModule.candidat");
	}

	/**
	 * @deprecated Use 'candidat.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emploitocndixmodule.proxies.candidat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emploitocndixmodule.proxies.candidat.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emploitocndixmodule.proxies.candidat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emploitocndixmodule.proxies.candidat(context, mendixObject);
	}

	public static emploitocndixmodule.proxies.candidat load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emploitocndixmodule.proxies.candidat.initialize(context, mendixObject);
	}

	public static java.util.List<emploitocndixmodule.proxies.candidat> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emploitocndixmodule.proxies.candidat> result = new java.util.ArrayList<emploitocndixmodule.proxies.candidat>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//emploiTocndixModule.candidat" + xpathConstraint))
			result.add(emploitocndixmodule.proxies.candidat.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of nom
	 */
	public final java.lang.String getnom()
	{
		return getnom(getContext());
	}

	/**
	 * @param context
	 * @return value of nom
	 */
	public final java.lang.String getnom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nom.toString());
	}

	/**
	 * Set value of nom
	 * @param nom
	 */
	public final void setnom(java.lang.String nom)
	{
		setnom(getContext(), nom);
	}

	/**
	 * Set value of nom
	 * @param context
	 * @param nom
	 */
	public final void setnom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nom)
	{
		getMendixObject().setValue(context, MemberNames.nom.toString(), nom);
	}

	/**
	 * @return value of prenom
	 */
	public final java.lang.String getprenom()
	{
		return getprenom(getContext());
	}

	/**
	 * @param context
	 * @return value of prenom
	 */
	public final java.lang.String getprenom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.prenom.toString());
	}

	/**
	 * Set value of prenom
	 * @param prenom
	 */
	public final void setprenom(java.lang.String prenom)
	{
		setprenom(getContext(), prenom);
	}

	/**
	 * Set value of prenom
	 * @param context
	 * @param prenom
	 */
	public final void setprenom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String prenom)
	{
		getMendixObject().setValue(context, MemberNames.prenom.toString(), prenom);
	}

	/**
	 * @return value of salaire_voulu
	 */
	public final java.math.BigDecimal getsalaire_voulu()
	{
		return getsalaire_voulu(getContext());
	}

	/**
	 * @param context
	 * @return value of salaire_voulu
	 */
	public final java.math.BigDecimal getsalaire_voulu(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.salaire_voulu.toString());
	}

	/**
	 * Set value of salaire_voulu
	 * @param salaire_voulu
	 */
	public final void setsalaire_voulu(java.math.BigDecimal salaire_voulu)
	{
		setsalaire_voulu(getContext(), salaire_voulu);
	}

	/**
	 * Set value of salaire_voulu
	 * @param context
	 * @param salaire_voulu
	 */
	public final void setsalaire_voulu(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal salaire_voulu)
	{
		getMendixObject().setValue(context, MemberNames.salaire_voulu.toString(), salaire_voulu);
	}

	/**
	 * @return value of email
	 */
	public final java.lang.String getemail()
	{
		return getemail(getContext());
	}

	/**
	 * @param context
	 * @return value of email
	 */
	public final java.lang.String getemail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.email.toString());
	}

	/**
	 * Set value of email
	 * @param email
	 */
	public final void setemail(java.lang.String email)
	{
		setemail(getContext(), email);
	}

	/**
	 * Set value of email
	 * @param context
	 * @param email
	 */
	public final void setemail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.email.toString(), email);
	}

	/**
	 * Set value of avis
	 * @param avis
	 */
	public final emploitocndixmodule.proxies.EnumerationAvis getavis()
	{
		return getavis(getContext());
	}

	/**
	 * @param context
	 * @return value of avis
	 */
	public final emploitocndixmodule.proxies.EnumerationAvis getavis(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.avis.toString());
		if (obj == null)
			return null;

		return emploitocndixmodule.proxies.EnumerationAvis.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of avis
	 * @param avis
	 */
	public final void setavis(emploitocndixmodule.proxies.EnumerationAvis avis)
	{
		setavis(getContext(), avis);
	}

	/**
	 * Set value of avis
	 * @param context
	 * @param avis
	 */
	public final void setavis(com.mendix.systemwideinterfaces.core.IContext context, emploitocndixmodule.proxies.EnumerationAvis avis)
	{
		if (avis != null)
			getMendixObject().setValue(context, MemberNames.avis.toString(), avis.toString());
		else
			getMendixObject().setValue(context, MemberNames.avis.toString(), null);
	}

	/**
	 * @return value of commentaire
	 */
	public final java.lang.String getcommentaire()
	{
		return getcommentaire(getContext());
	}

	/**
	 * @param context
	 * @return value of commentaire
	 */
	public final java.lang.String getcommentaire(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.commentaire.toString());
	}

	/**
	 * Set value of commentaire
	 * @param commentaire
	 */
	public final void setcommentaire(java.lang.String commentaire)
	{
		setcommentaire(getContext(), commentaire);
	}

	/**
	 * Set value of commentaire
	 * @param context
	 * @param commentaire
	 */
	public final void setcommentaire(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String commentaire)
	{
		getMendixObject().setValue(context, MemberNames.commentaire.toString(), commentaire);
	}

	/**
	 * @return value of candidat_offre
	 */
	public final emploitocndixmodule.proxies.offre getcandidat_offre() throws com.mendix.core.CoreException
	{
		return getcandidat_offre(getContext());
	}

	/**
	 * @param context
	 * @return value of candidat_offre
	 */
	public final emploitocndixmodule.proxies.offre getcandidat_offre(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emploitocndixmodule.proxies.offre result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.candidat_offre.toString());
		if (identifier != null)
			result = emploitocndixmodule.proxies.offre.load(context, identifier);
		return result;
	}

	/**
	 * Set value of candidat_offre
	 * @param candidat_offre
	 */
	public final void setcandidat_offre(emploitocndixmodule.proxies.offre candidat_offre)
	{
		setcandidat_offre(getContext(), candidat_offre);
	}

	/**
	 * Set value of candidat_offre
	 * @param context
	 * @param candidat_offre
	 */
	public final void setcandidat_offre(com.mendix.systemwideinterfaces.core.IContext context, emploitocndixmodule.proxies.offre candidat_offre)
	{
		if (candidat_offre == null)
			getMendixObject().setValue(context, MemberNames.candidat_offre.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.candidat_offre.toString(), candidat_offre.getMendixObject().getId());
	}

	/**
	 * @return value of candidat_cv
	 */
	public final emploitocndixmodule.proxies.cv getcandidat_cv() throws com.mendix.core.CoreException
	{
		return getcandidat_cv(getContext());
	}

	/**
	 * @param context
	 * @return value of candidat_cv
	 */
	public final emploitocndixmodule.proxies.cv getcandidat_cv(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emploitocndixmodule.proxies.cv result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.candidat_cv.toString());
		if (identifier != null)
			result = emploitocndixmodule.proxies.cv.load(context, identifier);
		return result;
	}

	/**
	 * Set value of candidat_cv
	 * @param candidat_cv
	 */
	public final void setcandidat_cv(emploitocndixmodule.proxies.cv candidat_cv)
	{
		setcandidat_cv(getContext(), candidat_cv);
	}

	/**
	 * Set value of candidat_cv
	 * @param context
	 * @param candidat_cv
	 */
	public final void setcandidat_cv(com.mendix.systemwideinterfaces.core.IContext context, emploitocndixmodule.proxies.cv candidat_cv)
	{
		if (candidat_cv == null)
			getMendixObject().setValue(context, MemberNames.candidat_cv.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.candidat_cv.toString(), candidat_cv.getMendixObject().getId());
	}

	/**
	 * @return value of candidat_motivation
	 */
	public final emploitocndixmodule.proxies.motivation getcandidat_motivation() throws com.mendix.core.CoreException
	{
		return getcandidat_motivation(getContext());
	}

	/**
	 * @param context
	 * @return value of candidat_motivation
	 */
	public final emploitocndixmodule.proxies.motivation getcandidat_motivation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emploitocndixmodule.proxies.motivation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.candidat_motivation.toString());
		if (identifier != null)
			result = emploitocndixmodule.proxies.motivation.load(context, identifier);
		return result;
	}

	/**
	 * Set value of candidat_motivation
	 * @param candidat_motivation
	 */
	public final void setcandidat_motivation(emploitocndixmodule.proxies.motivation candidat_motivation)
	{
		setcandidat_motivation(getContext(), candidat_motivation);
	}

	/**
	 * Set value of candidat_motivation
	 * @param context
	 * @param candidat_motivation
	 */
	public final void setcandidat_motivation(com.mendix.systemwideinterfaces.core.IContext context, emploitocndixmodule.proxies.motivation candidat_motivation)
	{
		if (candidat_motivation == null)
			getMendixObject().setValue(context, MemberNames.candidat_motivation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.candidat_motivation.toString(), candidat_motivation.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emploitocndixmodule.proxies.candidat that = (emploitocndixmodule.proxies.candidat) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "emploiTocndixModule.candidat";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
