// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emploitocndixmodule.proxies;

public class candidat
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject candidatMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "emploiTocndixModule.candidat";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		nom("nom"),
		prenom("prenom"),
		cv_lien("cv_lien"),
		salaire_voulu("salaire_voulu"),
		lettre_motivation("lettre_motivation"),
		email("email"),
		candidat_offre("emploiTocndixModule.candidat_offre"),
		candidat_commentaire("emploiTocndixModule.candidat_commentaire");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public candidat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "emploiTocndixModule.candidat"));
	}

	protected candidat(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject candidatMendixObject)
	{
		if (candidatMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("emploiTocndixModule.candidat", candidatMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a emploiTocndixModule.candidat");

		this.candidatMendixObject = candidatMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'candidat.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emploitocndixmodule.proxies.candidat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emploitocndixmodule.proxies.candidat.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emploitocndixmodule.proxies.candidat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emploitocndixmodule.proxies.candidat(context, mendixObject);
	}

	public static emploitocndixmodule.proxies.candidat load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emploitocndixmodule.proxies.candidat.initialize(context, mendixObject);
	}

	public static java.util.List<emploitocndixmodule.proxies.candidat> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emploitocndixmodule.proxies.candidat> result = new java.util.ArrayList<emploitocndixmodule.proxies.candidat>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//emploiTocndixModule.candidat" + xpathConstraint))
			result.add(emploitocndixmodule.proxies.candidat.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of nom
	 */
	public final java.lang.String getnom()
	{
		return getnom(getContext());
	}

	/**
	 * @param context
	 * @return value of nom
	 */
	public final java.lang.String getnom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nom.toString());
	}

	/**
	 * Set value of nom
	 * @param nom
	 */
	public final void setnom(java.lang.String nom)
	{
		setnom(getContext(), nom);
	}

	/**
	 * Set value of nom
	 * @param context
	 * @param nom
	 */
	public final void setnom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nom)
	{
		getMendixObject().setValue(context, MemberNames.nom.toString(), nom);
	}

	/**
	 * @return value of prenom
	 */
	public final java.lang.String getprenom()
	{
		return getprenom(getContext());
	}

	/**
	 * @param context
	 * @return value of prenom
	 */
	public final java.lang.String getprenom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.prenom.toString());
	}

	/**
	 * Set value of prenom
	 * @param prenom
	 */
	public final void setprenom(java.lang.String prenom)
	{
		setprenom(getContext(), prenom);
	}

	/**
	 * Set value of prenom
	 * @param context
	 * @param prenom
	 */
	public final void setprenom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String prenom)
	{
		getMendixObject().setValue(context, MemberNames.prenom.toString(), prenom);
	}

	/**
	 * @return value of cv_lien
	 */
	public final java.lang.String getcv_lien()
	{
		return getcv_lien(getContext());
	}

	/**
	 * @param context
	 * @return value of cv_lien
	 */
	public final java.lang.String getcv_lien(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.cv_lien.toString());
	}

	/**
	 * Set value of cv_lien
	 * @param cv_lien
	 */
	public final void setcv_lien(java.lang.String cv_lien)
	{
		setcv_lien(getContext(), cv_lien);
	}

	/**
	 * Set value of cv_lien
	 * @param context
	 * @param cv_lien
	 */
	public final void setcv_lien(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cv_lien)
	{
		getMendixObject().setValue(context, MemberNames.cv_lien.toString(), cv_lien);
	}

	/**
	 * @return value of salaire_voulu
	 */
	public final java.math.BigDecimal getsalaire_voulu()
	{
		return getsalaire_voulu(getContext());
	}

	/**
	 * @param context
	 * @return value of salaire_voulu
	 */
	public final java.math.BigDecimal getsalaire_voulu(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.salaire_voulu.toString());
	}

	/**
	 * Set value of salaire_voulu
	 * @param salaire_voulu
	 */
	public final void setsalaire_voulu(java.math.BigDecimal salaire_voulu)
	{
		setsalaire_voulu(getContext(), salaire_voulu);
	}

	/**
	 * Set value of salaire_voulu
	 * @param context
	 * @param salaire_voulu
	 */
	public final void setsalaire_voulu(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal salaire_voulu)
	{
		getMendixObject().setValue(context, MemberNames.salaire_voulu.toString(), salaire_voulu);
	}

	/**
	 * @return value of lettre_motivation
	 */
	public final java.lang.String getlettre_motivation()
	{
		return getlettre_motivation(getContext());
	}

	/**
	 * @param context
	 * @return value of lettre_motivation
	 */
	public final java.lang.String getlettre_motivation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.lettre_motivation.toString());
	}

	/**
	 * Set value of lettre_motivation
	 * @param lettre_motivation
	 */
	public final void setlettre_motivation(java.lang.String lettre_motivation)
	{
		setlettre_motivation(getContext(), lettre_motivation);
	}

	/**
	 * Set value of lettre_motivation
	 * @param context
	 * @param lettre_motivation
	 */
	public final void setlettre_motivation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lettre_motivation)
	{
		getMendixObject().setValue(context, MemberNames.lettre_motivation.toString(), lettre_motivation);
	}

	/**
	 * @return value of email
	 */
	public final java.lang.String getemail()
	{
		return getemail(getContext());
	}

	/**
	 * @param context
	 * @return value of email
	 */
	public final java.lang.String getemail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.email.toString());
	}

	/**
	 * Set value of email
	 * @param email
	 */
	public final void setemail(java.lang.String email)
	{
		setemail(getContext(), email);
	}

	/**
	 * Set value of email
	 * @param context
	 * @param email
	 */
	public final void setemail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.email.toString(), email);
	}

	/**
	 * @return value of candidat_offre
	 */
	public final emploitocndixmodule.proxies.offre getcandidat_offre() throws com.mendix.core.CoreException
	{
		return getcandidat_offre(getContext());
	}

	/**
	 * @param context
	 * @return value of candidat_offre
	 */
	public final emploitocndixmodule.proxies.offre getcandidat_offre(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emploitocndixmodule.proxies.offre result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.candidat_offre.toString());
		if (identifier != null)
			result = emploitocndixmodule.proxies.offre.load(context, identifier);
		return result;
	}

	/**
	 * Set value of candidat_offre
	 * @param candidat_offre
	 */
	public final void setcandidat_offre(emploitocndixmodule.proxies.offre candidat_offre)
	{
		setcandidat_offre(getContext(), candidat_offre);
	}

	/**
	 * Set value of candidat_offre
	 * @param context
	 * @param candidat_offre
	 */
	public final void setcandidat_offre(com.mendix.systemwideinterfaces.core.IContext context, emploitocndixmodule.proxies.offre candidat_offre)
	{
		if (candidat_offre == null)
			getMendixObject().setValue(context, MemberNames.candidat_offre.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.candidat_offre.toString(), candidat_offre.getMendixObject().getId());
	}

	/**
	 * @return value of candidat_commentaire
	 */
	public final emploitocndixmodule.proxies.commentaire getcandidat_commentaire() throws com.mendix.core.CoreException
	{
		return getcandidat_commentaire(getContext());
	}

	/**
	 * @param context
	 * @return value of candidat_commentaire
	 */
	public final emploitocndixmodule.proxies.commentaire getcandidat_commentaire(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emploitocndixmodule.proxies.commentaire result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.candidat_commentaire.toString());
		if (identifier != null)
			result = emploitocndixmodule.proxies.commentaire.load(context, identifier);
		return result;
	}

	/**
	 * Set value of candidat_commentaire
	 * @param candidat_commentaire
	 */
	public final void setcandidat_commentaire(emploitocndixmodule.proxies.commentaire candidat_commentaire)
	{
		setcandidat_commentaire(getContext(), candidat_commentaire);
	}

	/**
	 * Set value of candidat_commentaire
	 * @param context
	 * @param candidat_commentaire
	 */
	public final void setcandidat_commentaire(com.mendix.systemwideinterfaces.core.IContext context, emploitocndixmodule.proxies.commentaire candidat_commentaire)
	{
		if (candidat_commentaire == null)
			getMendixObject().setValue(context, MemberNames.candidat_commentaire.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.candidat_commentaire.toString(), candidat_commentaire.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return candidatMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emploitocndixmodule.proxies.candidat that = (emploitocndixmodule.proxies.candidat) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "emploiTocndixModule.candidat";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
