// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emploitocndixmodule.proxies;

public enum EnumerationAvis
{
	A__tudier(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "fr_FR", "A étudier" } }),
	Non_recevable(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "fr_FR", "Non recevable" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private EnumerationAvis(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("fr_FR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("fr_FR");
	}
}
