// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emploitocndixmodule.proxies;

public class kpi
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject kpiMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "emploiTocndixModule.kpi";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		nb_cv("nb_cv"),
		dechet("dechet"),
		cout("cout"),
		kpi_offre("emploiTocndixModule.kpi_offre");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public kpi(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "emploiTocndixModule.kpi"));
	}

	protected kpi(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject kpiMendixObject)
	{
		if (kpiMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("emploiTocndixModule.kpi", kpiMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a emploiTocndixModule.kpi");

		this.kpiMendixObject = kpiMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'kpi.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emploitocndixmodule.proxies.kpi initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emploitocndixmodule.proxies.kpi.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emploitocndixmodule.proxies.kpi initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emploitocndixmodule.proxies.kpi(context, mendixObject);
	}

	public static emploitocndixmodule.proxies.kpi load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emploitocndixmodule.proxies.kpi.initialize(context, mendixObject);
	}

	public static java.util.List<emploitocndixmodule.proxies.kpi> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emploitocndixmodule.proxies.kpi> result = new java.util.ArrayList<emploitocndixmodule.proxies.kpi>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//emploiTocndixModule.kpi" + xpathConstraint))
			result.add(emploitocndixmodule.proxies.kpi.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of nb_cv
	 */
	public final java.lang.Integer getnb_cv()
	{
		return getnb_cv(getContext());
	}

	/**
	 * @param context
	 * @return value of nb_cv
	 */
	public final java.lang.Integer getnb_cv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.nb_cv.toString());
	}

	/**
	 * Set value of nb_cv
	 * @param nb_cv
	 */
	public final void setnb_cv(java.lang.Integer nb_cv)
	{
		setnb_cv(getContext(), nb_cv);
	}

	/**
	 * Set value of nb_cv
	 * @param context
	 * @param nb_cv
	 */
	public final void setnb_cv(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nb_cv)
	{
		getMendixObject().setValue(context, MemberNames.nb_cv.toString(), nb_cv);
	}

	/**
	 * @return value of dechet
	 */
	public final java.math.BigDecimal getdechet()
	{
		return getdechet(getContext());
	}

	/**
	 * @param context
	 * @return value of dechet
	 */
	public final java.math.BigDecimal getdechet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.dechet.toString());
	}

	/**
	 * Set value of dechet
	 * @param dechet
	 */
	public final void setdechet(java.math.BigDecimal dechet)
	{
		setdechet(getContext(), dechet);
	}

	/**
	 * Set value of dechet
	 * @param context
	 * @param dechet
	 */
	public final void setdechet(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal dechet)
	{
		getMendixObject().setValue(context, MemberNames.dechet.toString(), dechet);
	}

	/**
	 * @return value of cout
	 */
	public final java.math.BigDecimal getcout()
	{
		return getcout(getContext());
	}

	/**
	 * @param context
	 * @return value of cout
	 */
	public final java.math.BigDecimal getcout(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.cout.toString());
	}

	/**
	 * Set value of cout
	 * @param cout
	 */
	public final void setcout(java.math.BigDecimal cout)
	{
		setcout(getContext(), cout);
	}

	/**
	 * Set value of cout
	 * @param context
	 * @param cout
	 */
	public final void setcout(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal cout)
	{
		getMendixObject().setValue(context, MemberNames.cout.toString(), cout);
	}

	/**
	 * @return value of kpi_offre
	 */
	public final emploitocndixmodule.proxies.offre getkpi_offre() throws com.mendix.core.CoreException
	{
		return getkpi_offre(getContext());
	}

	/**
	 * @param context
	 * @return value of kpi_offre
	 */
	public final emploitocndixmodule.proxies.offre getkpi_offre(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emploitocndixmodule.proxies.offre result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.kpi_offre.toString());
		if (identifier != null)
			result = emploitocndixmodule.proxies.offre.load(context, identifier);
		return result;
	}

	/**
	 * Set value of kpi_offre
	 * @param kpi_offre
	 */
	public final void setkpi_offre(emploitocndixmodule.proxies.offre kpi_offre)
	{
		setkpi_offre(getContext(), kpi_offre);
	}

	/**
	 * Set value of kpi_offre
	 * @param context
	 * @param kpi_offre
	 */
	public final void setkpi_offre(com.mendix.systemwideinterfaces.core.IContext context, emploitocndixmodule.proxies.offre kpi_offre)
	{
		if (kpi_offre == null)
			getMendixObject().setValue(context, MemberNames.kpi_offre.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.kpi_offre.toString(), kpi_offre.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return kpiMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emploitocndixmodule.proxies.kpi that = (emploitocndixmodule.proxies.kpi) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "emploiTocndixModule.kpi";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
