// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emploitocndixmodule.proxies;

public class motivation extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "emploiTocndixModule.motivation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		candidat_motivation("emploiTocndixModule.candidat_motivation");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public motivation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "emploiTocndixModule.motivation"));
	}

	protected motivation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject motivationMendixObject)
	{
		super(context, motivationMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("emploiTocndixModule.motivation", motivationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a emploiTocndixModule.motivation");
	}

	/**
	 * @deprecated Use 'motivation.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emploitocndixmodule.proxies.motivation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emploitocndixmodule.proxies.motivation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emploitocndixmodule.proxies.motivation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emploitocndixmodule.proxies.motivation(context, mendixObject);
	}

	public static emploitocndixmodule.proxies.motivation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emploitocndixmodule.proxies.motivation.initialize(context, mendixObject);
	}

	public static java.util.List<emploitocndixmodule.proxies.motivation> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emploitocndixmodule.proxies.motivation> result = new java.util.ArrayList<emploitocndixmodule.proxies.motivation>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//emploiTocndixModule.motivation" + xpathConstraint))
			result.add(emploitocndixmodule.proxies.motivation.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of candidat_motivation
	 */
	public final emploitocndixmodule.proxies.candidat getcandidat_motivation() throws com.mendix.core.CoreException
	{
		return getcandidat_motivation(getContext());
	}

	/**
	 * @param context
	 * @return value of candidat_motivation
	 */
	public final emploitocndixmodule.proxies.candidat getcandidat_motivation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emploitocndixmodule.proxies.candidat result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.candidat_motivation.toString());
		if (identifier != null)
			result = emploitocndixmodule.proxies.candidat.load(context, identifier);
		return result;
	}

	/**
	 * Set value of candidat_motivation
	 * @param candidat_motivation
	 */
	public final void setcandidat_motivation(emploitocndixmodule.proxies.candidat candidat_motivation)
	{
		setcandidat_motivation(getContext(), candidat_motivation);
	}

	/**
	 * Set value of candidat_motivation
	 * @param context
	 * @param candidat_motivation
	 */
	public final void setcandidat_motivation(com.mendix.systemwideinterfaces.core.IContext context, emploitocndixmodule.proxies.candidat candidat_motivation)
	{
		if (candidat_motivation == null)
			getMendixObject().setValue(context, MemberNames.candidat_motivation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.candidat_motivation.toString(), candidat_motivation.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emploitocndixmodule.proxies.motivation that = (emploitocndixmodule.proxies.motivation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "emploiTocndixModule.motivation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
