// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emploitocndixmodule.proxies;

public class offre_canal
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject offre_canalMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "emploiTocndixModule.offre_canal";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		date_publication("date_publication"),
		offre_canal_offre("emploiTocndixModule.offre_canal_offre"),
		offre_canal_canal("emploiTocndixModule.offre_canal_canal");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public offre_canal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "emploiTocndixModule.offre_canal"));
	}

	protected offre_canal(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject offre_canalMendixObject)
	{
		if (offre_canalMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("emploiTocndixModule.offre_canal", offre_canalMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a emploiTocndixModule.offre_canal");

		this.offre_canalMendixObject = offre_canalMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'offre_canal.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emploitocndixmodule.proxies.offre_canal initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emploitocndixmodule.proxies.offre_canal.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emploitocndixmodule.proxies.offre_canal initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emploitocndixmodule.proxies.offre_canal(context, mendixObject);
	}

	public static emploitocndixmodule.proxies.offre_canal load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emploitocndixmodule.proxies.offre_canal.initialize(context, mendixObject);
	}

	public static java.util.List<emploitocndixmodule.proxies.offre_canal> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emploitocndixmodule.proxies.offre_canal> result = new java.util.ArrayList<emploitocndixmodule.proxies.offre_canal>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//emploiTocndixModule.offre_canal" + xpathConstraint))
			result.add(emploitocndixmodule.proxies.offre_canal.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of date_publication
	 */
	public final java.util.Date getdate_publication()
	{
		return getdate_publication(getContext());
	}

	/**
	 * @param context
	 * @return value of date_publication
	 */
	public final java.util.Date getdate_publication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.date_publication.toString());
	}

	/**
	 * Set value of date_publication
	 * @param date_publication
	 */
	public final void setdate_publication(java.util.Date date_publication)
	{
		setdate_publication(getContext(), date_publication);
	}

	/**
	 * Set value of date_publication
	 * @param context
	 * @param date_publication
	 */
	public final void setdate_publication(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date_publication)
	{
		getMendixObject().setValue(context, MemberNames.date_publication.toString(), date_publication);
	}

	/**
	 * @return value of offre_canal_offre
	 */
	public final emploitocndixmodule.proxies.offre getoffre_canal_offre() throws com.mendix.core.CoreException
	{
		return getoffre_canal_offre(getContext());
	}

	/**
	 * @param context
	 * @return value of offre_canal_offre
	 */
	public final emploitocndixmodule.proxies.offre getoffre_canal_offre(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emploitocndixmodule.proxies.offre result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.offre_canal_offre.toString());
		if (identifier != null)
			result = emploitocndixmodule.proxies.offre.load(context, identifier);
		return result;
	}

	/**
	 * Set value of offre_canal_offre
	 * @param offre_canal_offre
	 */
	public final void setoffre_canal_offre(emploitocndixmodule.proxies.offre offre_canal_offre)
	{
		setoffre_canal_offre(getContext(), offre_canal_offre);
	}

	/**
	 * Set value of offre_canal_offre
	 * @param context
	 * @param offre_canal_offre
	 */
	public final void setoffre_canal_offre(com.mendix.systemwideinterfaces.core.IContext context, emploitocndixmodule.proxies.offre offre_canal_offre)
	{
		if (offre_canal_offre == null)
			getMendixObject().setValue(context, MemberNames.offre_canal_offre.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.offre_canal_offre.toString(), offre_canal_offre.getMendixObject().getId());
	}

	/**
	 * @return value of offre_canal_canal
	 */
	public final emploitocndixmodule.proxies.canal getoffre_canal_canal() throws com.mendix.core.CoreException
	{
		return getoffre_canal_canal(getContext());
	}

	/**
	 * @param context
	 * @return value of offre_canal_canal
	 */
	public final emploitocndixmodule.proxies.canal getoffre_canal_canal(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emploitocndixmodule.proxies.canal result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.offre_canal_canal.toString());
		if (identifier != null)
			result = emploitocndixmodule.proxies.canal.load(context, identifier);
		return result;
	}

	/**
	 * Set value of offre_canal_canal
	 * @param offre_canal_canal
	 */
	public final void setoffre_canal_canal(emploitocndixmodule.proxies.canal offre_canal_canal)
	{
		setoffre_canal_canal(getContext(), offre_canal_canal);
	}

	/**
	 * Set value of offre_canal_canal
	 * @param context
	 * @param offre_canal_canal
	 */
	public final void setoffre_canal_canal(com.mendix.systemwideinterfaces.core.IContext context, emploitocndixmodule.proxies.canal offre_canal_canal)
	{
		if (offre_canal_canal == null)
			getMendixObject().setValue(context, MemberNames.offre_canal_canal.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.offre_canal_canal.toString(), offre_canal_canal.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return offre_canalMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emploitocndixmodule.proxies.offre_canal that = (emploitocndixmodule.proxies.offre_canal) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "emploiTocndixModule.offre_canal";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
