// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emploitocndixmodule.proxies;

public class site
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject siteMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "emploiTocndixModule.site";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		nom_site("nom_site"),
		adresse("adresse"),
		ville("ville"),
		site_pays("emploiTocndixModule.site_pays");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public site(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "emploiTocndixModule.site"));
	}

	protected site(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject siteMendixObject)
	{
		if (siteMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("emploiTocndixModule.site", siteMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a emploiTocndixModule.site");

		this.siteMendixObject = siteMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'site.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emploitocndixmodule.proxies.site initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emploitocndixmodule.proxies.site.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emploitocndixmodule.proxies.site initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emploitocndixmodule.proxies.site(context, mendixObject);
	}

	public static emploitocndixmodule.proxies.site load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emploitocndixmodule.proxies.site.initialize(context, mendixObject);
	}

	public static java.util.List<emploitocndixmodule.proxies.site> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emploitocndixmodule.proxies.site> result = new java.util.ArrayList<emploitocndixmodule.proxies.site>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//emploiTocndixModule.site" + xpathConstraint))
			result.add(emploitocndixmodule.proxies.site.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of nom_site
	 */
	public final java.lang.String getnom_site()
	{
		return getnom_site(getContext());
	}

	/**
	 * @param context
	 * @return value of nom_site
	 */
	public final java.lang.String getnom_site(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nom_site.toString());
	}

	/**
	 * Set value of nom_site
	 * @param nom_site
	 */
	public final void setnom_site(java.lang.String nom_site)
	{
		setnom_site(getContext(), nom_site);
	}

	/**
	 * Set value of nom_site
	 * @param context
	 * @param nom_site
	 */
	public final void setnom_site(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nom_site)
	{
		getMendixObject().setValue(context, MemberNames.nom_site.toString(), nom_site);
	}

	/**
	 * @return value of adresse
	 */
	public final java.lang.String getadresse()
	{
		return getadresse(getContext());
	}

	/**
	 * @param context
	 * @return value of adresse
	 */
	public final java.lang.String getadresse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.adresse.toString());
	}

	/**
	 * Set value of adresse
	 * @param adresse
	 */
	public final void setadresse(java.lang.String adresse)
	{
		setadresse(getContext(), adresse);
	}

	/**
	 * Set value of adresse
	 * @param context
	 * @param adresse
	 */
	public final void setadresse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String adresse)
	{
		getMendixObject().setValue(context, MemberNames.adresse.toString(), adresse);
	}

	/**
	 * @return value of ville
	 */
	public final java.lang.String getville()
	{
		return getville(getContext());
	}

	/**
	 * @param context
	 * @return value of ville
	 */
	public final java.lang.String getville(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ville.toString());
	}

	/**
	 * Set value of ville
	 * @param ville
	 */
	public final void setville(java.lang.String ville)
	{
		setville(getContext(), ville);
	}

	/**
	 * Set value of ville
	 * @param context
	 * @param ville
	 */
	public final void setville(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ville)
	{
		getMendixObject().setValue(context, MemberNames.ville.toString(), ville);
	}

	/**
	 * @return value of site_pays
	 */
	public final emploitocndixmodule.proxies.pays getsite_pays() throws com.mendix.core.CoreException
	{
		return getsite_pays(getContext());
	}

	/**
	 * @param context
	 * @return value of site_pays
	 */
	public final emploitocndixmodule.proxies.pays getsite_pays(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emploitocndixmodule.proxies.pays result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.site_pays.toString());
		if (identifier != null)
			result = emploitocndixmodule.proxies.pays.load(context, identifier);
		return result;
	}

	/**
	 * Set value of site_pays
	 * @param site_pays
	 */
	public final void setsite_pays(emploitocndixmodule.proxies.pays site_pays)
	{
		setsite_pays(getContext(), site_pays);
	}

	/**
	 * Set value of site_pays
	 * @param context
	 * @param site_pays
	 */
	public final void setsite_pays(com.mendix.systemwideinterfaces.core.IContext context, emploitocndixmodule.proxies.pays site_pays)
	{
		if (site_pays == null)
			getMendixObject().setValue(context, MemberNames.site_pays.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.site_pays.toString(), site_pays.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return siteMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emploitocndixmodule.proxies.site that = (emploitocndixmodule.proxies.site) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "emploiTocndixModule.site";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
