// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emploitocndixmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the emploiTocndixModule module
	public static emploitocndixmodule.proxies.cv microflowCv(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("emploiTocndixModule.MicroflowCv").withParams(params).execute(context);
		return result == null ? null : emploitocndixmodule.proxies.cv.initialize(context, result);
	}
	public static void microflowMotivation(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("emploiTocndixModule.MicroflowMotivation").withParams(params).execute(context);
	}
	public static emploitocndixmodule.proxies.candidats microflowNbCandidats(IContext context, emploitocndixmodule.proxies.offre _offre, emploitocndixmodule.proxies.candidats _candidats)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("offre", _offre == null ? null : _offre.getMendixObject());
		params.put("candidats", _candidats == null ? null : _candidats.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("emploiTocndixModule.MicroflowNbCandidats").withParams(params).execute(context);
		return result == null ? null : emploitocndixmodule.proxies.candidats.initialize(context, result);
	}
	public static java.util.List<emploitocndixmodule.proxies.candidat> microflowOffreCandidats(IContext context, emploitocndixmodule.proxies.offre _offre)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("offre", _offre == null ? null : _offre.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("emploiTocndixModule.MicroflowOffreCandidats").withParams(params).execute(context);
		java.util.List<emploitocndixmodule.proxies.candidat> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(emploitocndixmodule.proxies.candidat.initialize(context, obj));
		}
		return result;
	}
}